#! /bin/sh

# auto-start
killall "polybar"
~/docs/scripts/launch_polybar.sh &
killall "sxhkd"
pgrep -x sxhkd > /dev/null || sxhkd &
killall "lxpolki"
lxpolkit &
picom --experimental-backends &
killall "dunst"
dunst &
killall "flameshot"
flameshot &
/usr/bin/emacs --daemon &

brightnessctl set 100%
setxkbmap -option caps:escape &
xset r rate 300 50 &
xsetroot -cursor_name left_ptr
xset -dpms
xset s noblank
xset s off

# monitor Config
bspc monitor eDP -d 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -d 8 9 0

#bspwm Config
bspc config border_width        0
bspc config window_gap          15
bspc config top_padding         32
bspc config right_padding       8
bspc config left_padding        8
bspc config bottom_padding      8
bspc config window_gap          20

bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer-action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true

bspc rule -a Steam desktop='^5' state=floating follow=on
bspc rule -a lutris desktop='^5' state=floating follow=on
bspc rule -a Spotify desktop='^5'
bspc rule -a Discord desktop='^7'
bspc rule -a Screenkey manage=false
bspc rule -a Emacs state=tiling

# R psuedo-scratchpad
bspc rule -a kitty:R state=floating

# normal psuedo-scratchpad
bspc rule -a kitty:F state=floating

# "lock" screen
bspc rule -a kitty:A state=fullscreen

# pywal
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# pywal
rm ~/.cache/wal/schemes/*
wal -i ~/.config/wallpapers.png
